defmodule SbAuthEx.AuthController do
  @moduledoc """
  Handles the WorkOS AuthKit authentication flow.

  ## Login CSRF protection

  `login/2` starts an OAuth authorization-code flow with **PKCE** and a random
  **`state`** (both generated by `WorkOS.AuthKit.get_pkce_authorization_url/2`).
  The `state` and PKCE `code_verifier` are parked in a short-lived, encrypted,
  `HttpOnly` cookie bound to the browser that started the login.

  `callback/2` refuses to exchange the authorization code unless the `state`
  query parameter matches the cookie (compared with
  `Plug.Crypto.secure_compare/2`). Without this check an attacker could hand a
  victim their own `?code=` and have the victim's session bound to the
  attacker's account (login CSRF). The `code_verifier` is then sent along with
  the code, so a leaked code alone cannot be redeemed.

  The cookie — rather than the Phoenix session — is used for the same reason as
  the `return_to` cookie: it is explicitly `SameSite=Lax`, so it survives the
  cross-site redirect back from WorkOS regardless of how the host app
  configured its session cookie.
  """
  use Phoenix.Controller, formats: [:html, :json]
  import Plug.Conn

  alias SbAuthEx.Accounts
  alias SbAuthEx.WorkOSClient

  @return_to_cookie "_sb_auth_return_to"
  @oauth_cookie "_sb_auth_oauth"
  @oauth_cookie_max_age 600

  @doc """
  Initiates the AuthKit login flow by redirecting to the WorkOS hosted UI.

  Accepts an optional `return_to` query parameter. If present, stores it in a
  signed cookie so the user can be redirected back after authentication.

  Mints a fresh `state` + PKCE pair for this login attempt and stores them in
  an encrypted cookie for `callback/2` to verify.
  """
  def login(conn, params) do
    conn = store_return_to_cookie(conn, params)

    %{url: url, code_verifier: code_verifier, state: state} =
      WorkOS.AuthKit.get_pkce_authorization_url(WorkOSClient.client(), %{
        provider: "authkit",
        redirect_uri: WorkOSClient.redirect_uri(),
        # Force account selection on every login to allow switching accounts
        prompt: "select_account"
      })

    conn
    |> store_oauth_cookie(state, code_verifier)
    |> redirect(external: url)
  end

  @doc """
  Handles the OAuth callback from WorkOS after user authentication.

  Verifies the `state` parameter against the value minted by `login/2` before
  exchanging the authorization code. Any mismatch — missing cookie, missing
  or wrong `state` — aborts the login without contacting WorkOS.
  """
  def callback(conn, params) do
    {conn, expected} = consume_oauth_cookie(conn)

    with :ok <- check_provider_error(params),
         {:ok, code} <- fetch_code(params),
         {:ok, code_verifier} <- verify_state(expected, params["state"]),
         {:ok, auth} <- exchange_code(code, code_verifier) do
      handle_successful_auth(conn, auth)
    else
      {:error, reason} ->
        conn
        |> clear_return_to_cookie()
        |> put_flash(:error, failure_message(reason))
        |> redirect(to: SbAuthEx.after_logout_path())
    end
  end

  @doc """
  Logs out the current user by clearing the session and redirecting to WorkOS logout.

  Fires the `on_logout` callback (if configured) before clearing the session.
  """
  def logout(conn, _params) do
    # Fire on_logout callback while identity is still available
    maybe_call_on_logout(conn)

    session_id = get_session(conn, :workos_session_id)

    # Clear local session first
    conn = configure_session(conn, drop: true)

    # If we have a WorkOS session ID, end the WorkOS session too by sending the
    # browser through the hosted logout endpoint (a pure URL build, no API call).
    if session_id do
      return_to = SbAuthEx.after_logout_path()
      endpoint = Application.get_env(:sb_auth_ex, :endpoint)
      full_return_to = if endpoint, do: endpoint.url() <> return_to, else: return_to

      logout_url =
        WorkOS.UserManagement.get_logout_url(WorkOSClient.client(), %{
          session_id: session_id,
          return_to: full_return_to
        })

      redirect(conn, external: logout_url)
    else
      conn
      |> put_flash(:info, "You have been logged out.")
      |> redirect(to: SbAuthEx.after_logout_path())
    end
  end

  @doc """
  Deletes the current user's account.

  Requires `current_identity` in conn assigns. Delegates to `SbAuthEx.delete_account/2`
  for the full deletion flow (callback, WorkOS, identity cleanup).
  The endpoint is idempotent: returns `{"deleted": true}` even if
  the identity was already removed.
  """
  def delete_account(conn, _params) do
    identity = conn.assigns[:current_identity]

    if identity do
      case SbAuthEx.delete_account(identity, conn) do
        {:ok, :deleted} ->
          conn
          |> configure_session(drop: true)
          |> put_status(200)
          |> json(%{deleted: true})

        {:error, {:cleanup_failed, reason}} ->
          conn
          |> put_status(422)
          |> json(%{error: "Cleanup failed: #{inspect(reason)}"})

        {:error, _reason} ->
          conn
          |> put_status(500)
          |> json(%{error: "Failed to delete account"})
      end
    else
      conn
      |> put_status(401)
      |> json(%{error: "Not authenticated"})
    end
  end

  # ---------------------------------------------------------------------------
  # Callback steps
  # ---------------------------------------------------------------------------

  # WorkOS reports user-facing failures (cancelled login, denied access, ...)
  # as ?error=...&error_description=... instead of ?code=...
  defp check_provider_error(%{"error" => error} = params) when is_binary(error) do
    {:error, {:provider_error, error, params["error_description"]}}
  end

  defp check_provider_error(_params), do: :ok

  defp fetch_code(%{"code" => code}) when is_binary(code) and code != "", do: {:ok, code}
  defp fetch_code(_params), do: {:error, :missing_code}

  defp verify_state(%{state: expected, code_verifier: code_verifier}, provided)
       when is_binary(expected) and is_binary(provided) do
    if Plug.Crypto.secure_compare(expected, provided) do
      {:ok, code_verifier}
    else
      {:error, :invalid_state}
    end
  end

  defp verify_state(nil, _provided), do: {:error, :missing_oauth_cookie}
  defp verify_state(_expected, _provided), do: {:error, :missing_state}

  defp exchange_code(code, code_verifier) do
    WorkOS.UserManagement.authenticate_with_code(WorkOSClient.client(), %{
      code: code,
      code_verifier: code_verifier
    })
  end

  defp failure_message({:provider_error, error, description}) do
    "Authentication failed: #{description || error}"
  end

  defp failure_message(:missing_code),
    do: "Authentication failed: missing authorization code"

  defp failure_message(reason)
       when reason in [:invalid_state, :missing_state, :missing_oauth_cookie] do
    "Authentication failed: invalid or expired login request. Please try again."
  end

  defp failure_message(:invalid_user_payload),
    do: "Authentication failed: unexpected response from WorkOS"

  defp failure_message(%{__exception__: true} = error),
    do: "Authentication failed: #{Exception.message(error)}"

  defp failure_message(reason), do: "Authentication failed: #{inspect(reason)}"

  defp handle_successful_auth(conn, %WorkOS.AuthenticateResponse{
         user: %WorkOS.User{id: user_id, email: email},
         access_token: access_token
       })
       when is_binary(user_id) and is_binary(email) do
    # Extract session_id from JWT access token
    session_id = extract_session_id(access_token)

    # Check if this is a new user BEFORE the upsert
    is_new_user = is_nil(Accounts.get_identity_by_sb_id(user_id))

    case Accounts.upsert_identity_from_provider!(user_id, email) do
      {:ok, identity} ->
        # For new users: fire on_register first, then on_login
        if is_new_user, do: maybe_call_on_register(conn, identity)
        maybe_call_on_login(conn, identity)

        {conn, redirect_to} = consume_return_to_cookie(conn)

        # Clear old session completely and set fresh values
        conn
        |> clear_session()
        |> put_session(:identity_id, identity.id)
        |> put_session(:workos_session_id, session_id)
        |> redirect(to: redirect_to)

      {:error, changeset} ->
        conn
        |> clear_return_to_cookie()
        |> put_flash(:error, "Failed to create account: #{inspect(changeset.errors)}")
        |> redirect(to: SbAuthEx.after_logout_path())
    end
  end

  defp handle_successful_auth(conn, _auth) do
    conn
    |> clear_return_to_cookie()
    |> put_flash(:error, failure_message(:invalid_user_payload))
    |> redirect(to: SbAuthEx.after_logout_path())
  end

  # ---------------------------------------------------------------------------
  # Lifecycle callbacks
  # ---------------------------------------------------------------------------

  defp maybe_call_on_login(conn, identity) do
    case Application.get_env(:sb_auth_ex, :on_login) do
      nil -> :ok
      {module, function} -> apply(module, function, [identity, conn])
      fun when is_function(fun, 2) -> fun.(identity, conn)
    end
  end

  defp maybe_call_on_register(conn, identity) do
    case Application.get_env(:sb_auth_ex, :on_register) do
      nil -> :ok
      {module, function} -> apply(module, function, [identity, conn])
      fun when is_function(fun, 2) -> fun.(identity, conn)
    end
  end

  defp maybe_call_on_logout(conn) do
    identity = conn.assigns[:current_identity]

    if identity do
      case Application.get_env(:sb_auth_ex, :on_logout) do
        nil -> :ok
        {module, function} -> apply(module, function, [identity, conn])
        fun when is_function(fun, 2) -> fun.(identity, conn)
      end
    end
  end

  # ---------------------------------------------------------------------------
  # OAuth state / PKCE cookie
  # ---------------------------------------------------------------------------

  defp store_oauth_cookie(conn, state, code_verifier) do
    put_resp_cookie(conn, @oauth_cookie, %{state: state, code_verifier: code_verifier},
      encrypt: true,
      max_age: @oauth_cookie_max_age,
      http_only: true,
      same_site: "Lax"
    )
  end

  # Reads and immediately invalidates the oauth cookie: each login attempt is
  # redeemable exactly once.
  defp consume_oauth_cookie(conn) do
    conn = fetch_cookies(conn, encrypted: [@oauth_cookie])

    expected =
      case conn.cookies[@oauth_cookie] do
        %{state: state, code_verifier: code_verifier} ->
          %{state: state, code_verifier: code_verifier}

        _ ->
          nil
      end

    {delete_resp_cookie(conn, @oauth_cookie), expected}
  end

  # ---------------------------------------------------------------------------
  # return_to cookie
  # ---------------------------------------------------------------------------

  defp store_return_to_cookie(conn, %{"return_to" => return_to})
       when is_binary(return_to) do
    if valid_return_to?(return_to) do
      put_resp_cookie(conn, @return_to_cookie, return_to,
        sign: true,
        max_age: 300,
        http_only: true,
        same_site: "Lax"
      )
    else
      clear_return_to_cookie(conn)
    end
  end

  defp store_return_to_cookie(conn, _params), do: clear_return_to_cookie(conn)

  defp consume_return_to_cookie(conn) do
    conn = fetch_cookies(conn, signed: [@return_to_cookie])
    return_to = conn.cookies[@return_to_cookie]
    conn = clear_return_to_cookie(conn)

    redirect_to =
      if valid_return_to?(return_to) do
        return_to
      else
        SbAuthEx.after_login_path()
      end

    {conn, redirect_to}
  end

  defp clear_return_to_cookie(conn), do: delete_resp_cookie(conn, @return_to_cookie)

  defp valid_return_to?(return_to) when is_binary(return_to) do
    String.starts_with?(return_to, "/") and not String.starts_with?(return_to, "//")
  end

  defp valid_return_to?(_return_to), do: false

  # ---------------------------------------------------------------------------
  # JWT helpers
  # ---------------------------------------------------------------------------

  defp extract_session_id(nil), do: nil

  defp extract_session_id(access_token) do
    # JWT is base64 encoded: header.payload.signature
    case String.split(access_token, ".") do
      [_header, payload, _signature] ->
        case Base.url_decode64(payload, padding: false) do
          {:ok, json} ->
            case Jason.decode(json) do
              {:ok, claims} -> claims["sid"]
              _ -> nil
            end

          _ ->
            nil
        end

      _ ->
        nil
    end
  end
end
